### login
GET http://localhost:4000/auth/login
Content-Type: application/json

{
  "email": "mshlool38@gmail.com",
  "password": "123123"
}

### register
POST http://localhost:4000/auth/register
Content-Type: application/json

{
  "email":"test1@gmail.com",
  "fullName":"shlool",
  "password":"123123"
}

#### send an email to user to reset password
GET http://localhost:4000/auth/reset-password
Content-Type: application/json

{
  "email":"mshlool38@gmail.com"
}

### the link in the email that was sent to reset password
PATCH localhost:4000/auth/reset-password?token=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtc2hsb29sMzhAZ21haWwuY29tIiwiaWF0IjoxNzU1NTA0MTA0LCJleHAiOjE3NTU1MTEzMDR9.bxbcd2HErYTNmcY3aJXLgE7GsCJJjc6Gv69SEoeu5kM
Content-Type: application/json

{
  "password":"123123"
}