### GET request to example server
POST http://localhost:4000/courses/create-course
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtc2hsb29sMzhAZ21haWwuY29tIiwicm9sZSI6Imluc3RydWN0b3IiLCJmdWxsTmFtZSI6Im1vaGFtYWQiLCJpYXQiOjE3NTU3NzYyMDMsImV4cCI6MTc1NTgxMjIwM30.IZl-fvT8vz6z5fKgvBHZvX5PdUKg8N4GquvOyvwRnj0
Content-Type: application/json

{
  "courseName": "kajsndj",
  "courseDescription": "askdkma",
  "courseLanguage": "aksmdkla",
  "coursePrice": 10,
  "instructorId": "0cd00610-4304-44ce-bdd6-9e31a7dc8bb8",
  "courseImage": {

  }
}

###